version: '3.5'

services:
  rpilocatorbot:
    # image: registry.gitlab.com/cbrown350/rpilocatorbot:latest
    build: .
    container_name: rpilocatorbot
    restart: unless-stopped
    environment:
      - TZ=America/Denver
      - LOG_LEVEL=debug
      - BOT_TOKEN=6276346945:AAGrOS67euXD7st5NZBJXS4D4C36mJfU6-Y
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sql:/sql
    # healthcheck:
    #   test: ["CMD", "curl", "-IX", "GET", "http://localhost:8000/logged-out"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    labels: 
      - "com.centurylinklabs.watchtower.enable=true"

